# Branches that trigger a build on commit
trigger:
- master
- master-vs-deps
- features/*
- demos/*
- dev16.0
- dev16.0-vs-deps
- dev16.1-preview1
- dev16.1-preview1-vs-deps

# Branches that trigger builds on PR
pr:
- master
- master-vs-deps
- features/*
- demos/*
- dev16.0
- dev16.0-vs-deps
- dev16.1-preview1
- dev16.1-preview1-vs-deps

jobs:

- job: Windows_CoreClr_Unit_Tests
  pool:
    vmImage: vs2017-win2016
  strategy:
    maxParallel: 1
    matrix:
      debug:
        _configuration: Debug
  timeoutInMinutes: 90

  steps:
    - script: eng/cibuild.cmd -configuration $(_configuration) -prepareMachine -msbuildEngine:dotnet -testCoreClr
      displayName: Build and Test

    - task: PublishTestResults@2
      displayName: Publish xUnit Test Results
      inputs:
        testRunner: XUnit
        testResultsFiles: '$(Build.SourcesDirectory)\artifacts\TestResults\$(_configuration)\*.xml'
        mergeTestResults: true
        testRunTitle: 'Windows CoreClr $(_configuration)'
      condition: always()

    - task: PublishBuildArtifacts@1
      displayName: Publish Logs
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)\artifacts\bin'
        ArtifactName: 'Windows CoreClr $(_configuration)'
        publishLocation: Container
      continueOnError: true
      condition: not(succeeded())